services:
  mysql:
    image: mariadb:11.4
    container_name: csmp-mysql
    restart: always
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: csmp-phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      PMA_PMADB: phpmyadmin
      PMA_CONTROLUSER: root
      PMA_CONTROLPASS: ${DB_ROOT_PASSWORD}
      PMA_THEME: metro
    ports:
      - "8080:80"

volumes:
  mysql_data: {}
